import { mkdir, rm } from 'node:fs/promises'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { queryTestRunDetails, updateAllParquet } from './analytics.js'
import {
  makeAcilIterationRecord,
  makeScilIterationRecord,
  makeTmpDir,
  writeAcilRunFixture,
  writeRunFixture,
  writeScilRunFixture,
} from './analytics-test-helpers.js'
import { queryAcilRunDetails, queryScilRunDetails } from './run-status.js'
import { InvalidRunIdError } from './types.js'

// ─── validateRunId (tested via exported functions) ────────────────────────────
//
// Real run IDs are generated by generateRunId() which produces YYYYMMDDTHHmmss.
// The validator rejects anything that doesn't match /^\d{8}T\d{6}$/.

describe('validateRunId', () => {
  describe('via queryTestRunDetails', () => {
    it('passes validation for a correctly-formatted run ID', async () => {
      const err = await queryTestRunDetails('/nonexistent', '20260327T120000').catch((e) => e)
      expect(err).not.toBeInstanceOf(InvalidRunIdError)
    })

    it('rejects a run ID using dash separator instead of T', async () => {
      await expect(queryTestRunDetails('/any', '20260327-120000')).rejects.toThrow(InvalidRunIdError)
    })

    it('rejects an empty string', async () => {
      await expect(queryTestRunDetails('/any', '')).rejects.toThrow(InvalidRunIdError)
    })

    it('rejects a SQL injection payload', async () => {
      const payload = "'; SELECT * FROM read_csv('/etc/passwd') --"
      await expect(queryTestRunDetails('/any', payload)).rejects.toThrow(InvalidRunIdError)
    })

    it('rejects a payload that starts with a valid-looking prefix but has trailing content', async () => {
      const payload = "20260327T120000' UNION SELECT * FROM read_parquet('/etc/passwd') --"
      await expect(queryTestRunDetails('/any', payload)).rejects.toThrow(InvalidRunIdError)
    })
  })

  describe('via queryScilRunDetails', () => {
    it('passes validation for a correctly-formatted run ID', async () => {
      const err = await queryScilRunDetails('/nonexistent', '20260327T120000').catch((e) => e)
      expect(err).not.toBeInstanceOf(InvalidRunIdError)
    })

    it('rejects a run ID that does not match the format', async () => {
      await expect(queryScilRunDetails('/any', 'bad-id')).rejects.toThrow(InvalidRunIdError)
    })

    it('rejects a SQL injection payload', async () => {
      const payload = "'; DROP TABLE test_results --"
      await expect(queryScilRunDetails('/any', payload)).rejects.toThrow(InvalidRunIdError)
    })
  })

  describe('via queryAcilRunDetails', () => {
    it('passes validation for a correctly-formatted run ID', async () => {
      const err = await queryAcilRunDetails('/nonexistent', '20260327T120000').catch((e) => e)
      expect(err).not.toBeInstanceOf(InvalidRunIdError)
    })

    it('rejects a run ID that does not match the format', async () => {
      await expect(queryAcilRunDetails('/any', 'bad-id')).rejects.toThrow(InvalidRunIdError)
    })

    it('rejects a SQL injection payload', async () => {
      const payload = "'; DROP TABLE test_results --"
      await expect(queryAcilRunDetails('/any', payload)).rejects.toThrow(InvalidRunIdError)
    })
  })
})

// ─── integration: crafted runId is rejected before reaching DuckDB ───────────

describe('SQL injection rejection (integration)', () => {
  let tmpDir: string
  let outputDir: string
  let dataDir: string

  beforeEach(async () => {
    tmpDir = await makeTmpDir()
    outputDir = `${tmpDir}/output`
    dataDir = `${tmpDir}/data`
    await mkdir(dataDir, { recursive: true })

    await writeRunFixture({
      outputDir,
      testRunId: '20260327T120000',
      suite: 'test-suite',
      testName: 'a test',
    })
    await updateAllParquet({ outputDir, dataDir })

    await writeScilRunFixture({
      outputDir,
      runId: '20260327T120001',
      iterations: [makeScilIterationRecord({ test_run_id: '20260327T120001' })],
    })

    await writeAcilRunFixture({
      outputDir,
      runId: '20260327T120002',
      iterations: [makeAcilIterationRecord({ test_run_id: '20260327T120002' })],
    })
    await updateAllParquet({ outputDir, dataDir })
  })

  afterEach(async () => {
    await rm(tmpDir, { recursive: true, force: true })
  })

  it('rejects a crafted testRunId before executing any DuckDB query', async () => {
    const malicious = "20260327T120000' UNION SELECT content FROM read_text('/etc/passwd') --"
    await expect(queryTestRunDetails(dataDir, malicious)).rejects.toThrow(InvalidRunIdError)
  })

  it('rejects a crafted runId before executing any DuckDB query', async () => {
    const malicious = "20260327T120001'; SELECT * FROM read_json('/etc/hostname') --"
    await expect(queryScilRunDetails(dataDir, malicious)).rejects.toThrow(InvalidRunIdError)
  })

  it('rejects a crafted ACIL runId before executing any DuckDB query', async () => {
    const malicious = "20260327T120002'; SELECT * FROM read_json('/etc/hostname') --"
    await expect(queryAcilRunDetails(dataDir, malicious)).rejects.toThrow(InvalidRunIdError)
  })

  it('still queries successfully with a legitimate run ID after fixture setup', async () => {
    const result = await queryTestRunDetails(dataDir, '20260327T120000')
    expect(result.summary).toHaveLength(1)
  })
})
