export { ClaudeError } from './src/errors.js'
export type { OutputFile } from './src/extract-output-files.js'
export { extractOutputFiles } from './src/extract-output-files.js'
export { resolvePluginDirs } from './src/plugin-flags.js'
export { runClaude } from './src/run-claude.js'
export type { ClaudeRunOptions, ClaudeRunResult } from './src/types.js'
